apiVersion: v1
kind: Secret
metadata:
    name: dbackup-env
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:JOkmLjW0T08SC62wMFdgJ5QfGq5chmmmk4OHSLPVSupI2zS6jJt44x3AbRqlN3xhD+p2ax2Q1Xzf0HCZwu2ysQ==,iv:lQ6IOYMbQjqxW3UwRclveDPub49X7kWtd2rJOWkOwVA=,tag:n1wz4YiPEjPCeAXul0ZBrg==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:WZ3GxnT3LACfH97uc8Ntj/1LRO8=,iv:PCVJhiBLxzmPbr5+OLG7N1aj/N5wZITFXcSqeMlObrk=,tag:8+kcui7h4MFCPhVnozV0KQ==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:XNHenYefGGNev+2piJU5mIMPovLHyd4J9/3yNAC3hrhoo1aL4tP61PWw5Mw=,iv:7+tL+ujhBRqUujXA2xUFU04sJijEPai1eZ+qy8sZJ3c=,tag:sle/IGdzTKMbjnF7EhJGbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna3NmRUxXa2lra3M2OGdj
            Vi90SjFSUTRhOEl0eVJnUFMxbjJTWXR5eG5nClRhYWtGandTYUtWZ3pOMTFwa1hK
            aUdPd3JDenRIdU4xV3Q0WlgrR05yaEkKLS0tIFNFRC9PamRaWms1ZkZTSkZ2aHBo
            STJFeFNWWFZxNGFBb3lEWGlQeG5uVFkKPUBMLzfXFOfsgwMuc4gpddrrOe5ihNAN
            jgqGRj78y0lMuUUFMDiRFyzBNQSKSdRGI+t23zUi82vVhIl9hcA5XQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T18:12:57Z"
    mac: ENC[AES256_GCM,data:QyC8QKPlqHYfScICYIhkMu9Fjd+dMcIvAYyj0hE6PCbmL9GRXpSJlIBwr39sSvNX/iCFbixgiWlDjOoUYIwO1lADY+gbYvBs+Ec8Uqy35941VBqCAp02HCdqZszykWdcBsjXIwDgHKpDshTI83SJ1CxKi7Z+ZzKm4mjaUYDzaso=,iv:B0eSoW8SiF8ZDmkGrL5MZfOH7IUnhpDRJSqkM1Wv5hM=,tag:YfFqoUfN+mPQ5I4N0XERAg==,type:str]
    version: 3.13.2
