apiVersion: v1
kind: Secret
metadata:
    name: dbackup-env
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:dXqU8nUcXJq1Qfr7Opj3CXUJILNg/wyn5cb9/9gB2fVZtexaF87RayLVQpLSiDHm8JcRukmqmk+DX228H+TR1A==,iv:3xFV1+b6bAsiz8Zn+9auVrrfBEB7cq4IuF250DhXPtc=,tag:MMh7TXWoVUbRiMjZURJXWg==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:wa3sgKtxkKBnIM0L+HT3H54r36KeAA==,iv:qrfOVRUCjylzHDt07iRxWNYUYT+SsyrrwoO+jDfOUWA=,tag:NckQpTAsTPEg8h/qvbEEnQ==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:OgxLvXV/ddAYYOMgVMzgWsZbHdPggUHR1rAtLFcnpPN8+bTA30W3TIPxjkQ=,iv:nHtLNIm3mbjhby2JgWEpCsJr9YKI0tSRhsdjoS9IXGU=,tag:1SEInbTCYJIgcur0chJcFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWU0welVlV2RqbFhUWGFn
            VUJMVENHUkRpOG9hNmRUakxQbU9hbzNBeFhJCjFpVWpmVGpGVDVyQ1VlamY4SUZi
            Q0M0aVkvRGhvbmQxdHEvTGNLN0w5QmMKLS0tIHJYWGNIb3NsV294ZS85QzRla01X
            eHdFU29ORWpOZFNHZzhGbFhaZWdJd2sK41NLyEhL2ZwRynsgRvqz5DQLM96e+3PN
            p5HzizNycc1gQWLH1fN6hvvCa5f6GxahUrzhPasqHmr76wiKdlOEdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T18:14:53Z"
    mac: ENC[AES256_GCM,data:RyBX6U+G5vhnlqooJpAyDTu2MKDpkDluzO1nswFQItgV2Wp38EPS+oRj79hlWMb3/WUDqBfyONnmyzwaeTUKTHbYEcH2Nvg1yidxtT1ki2h8eOq7HstIwP4z1NmMFyLOiYE0o92DmHDQWes7Sw2JHWeeWOV36951++ZDAWfD5vM=,iv:+ZsYgWrQqucJcsVpxF0TJyELwURSqvkywWhnmjUvDw8=,tag:yLYQzgUFogpDlXzjbEXgDQ==,type:str]
    version: 3.13.2
