apiVersion: v1
kind: Secret
metadata:
    name: dbackup-env
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:JOkmLjW0T08SC62wMFdgJ5QfGq5chmmmk4OHSLPVSupI2zS6jJt44x3AbRqlN3xhD+p2ax2Q1Xzf0HCZwu2ysQ==,iv:lQ6IOYMbQjqxW3UwRclveDPub49X7kWtd2rJOWkOwVA=,tag:n1wz4YiPEjPCeAXul0ZBrg==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:FwZpHP9pzmgBWJtGYY6hiVDu6A==,iv:OYOVBtn3vArFaJZeEtYGMvBvAJHlprutha6KAyC+9Ek=,tag:qk38jsZ934giiQnaJNo2oA==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:XNHenYefGGNev+2piJU5mIMPovLHyd4J9/3yNAC3hrhoo1aL4tP61PWw5Mw=,iv:7+tL+ujhBRqUujXA2xUFU04sJijEPai1eZ+qy8sZJ3c=,tag:sle/IGdzTKMbjnF7EhJGbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna3NmRUxXa2lra3M2OGdj
            Vi90SjFSUTRhOEl0eVJnUFMxbjJTWXR5eG5nClRhYWtGandTYUtWZ3pOMTFwa1hK
            aUdPd3JDenRIdU4xV3Q0WlgrR05yaEkKLS0tIFNFRC9PamRaWms1ZkZTSkZ2aHBo
            STJFeFNWWFZxNGFBb3lEWGlQeG5uVFkKPUBMLzfXFOfsgwMuc4gpddrrOe5ihNAN
            jgqGRj78y0lMuUUFMDiRFyzBNQSKSdRGI+t23zUi82vVhIl9hcA5XQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T18:01:42Z"
    mac: ENC[AES256_GCM,data:9v6l6N4DYmTVgnuCS+BbRITdjJCrm9sC6Xj2ijkL4NdfPOB/WLFOxTCle+Au98JdFwHR+v0WYHJ5VJTi2yOluHtz7bOwzfNHqpwK1o/K9KS+3Vw3i3m8sJDMWvm4aFUbnc8xlfxOYLRWQ1C44B9APa2KDT9A/QhwJOSFw5cUamw=,iv:DXlSRPpAm5i+QG8Lv92MnubedbnYQ+bGoZ6Z7e29Po0=,tag:1SMCUzy1HTR97oqMSxktfg==,type:str]
    version: 3.13.2
