---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg-repo
  namespace: cloudnative-pg
  labels:
    app.kubernetes.io/name: cloudnative-pg-repo
spec:
  interval: 1h
  url: https://cloudnative-pg.github.io/charts
