apiVersion: v1
kind: Secret
metadata:
    name: backup-secret
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:3ysHxwDLWxI0IroRY/DcyvKiW78=,iv:QdaGw+bRfv3UxMN22CTJwV89Bi8sjJbElgZGUaqUTCM=,tag:goaVfuzogAlEp0NAZlxInQ==,type:str]
    secret-key: ENC[AES256_GCM,data:e5MaYEJXQLxwE21aakWdVAZUlZE=,iv:QAhYKnzdEVDU/C4PA2PEF16UsC54RLb5BRGgkh9iHZI=,tag:IBJZV9Xv0k3a5zaF29dZgw==,type:str]
    repo-ref: ENC[AES256_GCM,data:V9SDxNzuQP3zlHkwBfVYS2cZWnx6BdSzAkmlGqx5oCjqBSknzzjhNuClt/U=,iv:t83oKTi+hHf1bPf+V9SfclarT7Swof0ViY6DWRZ4VH8=,tag:xZflhovI+h9cIYDS8a+fMw==,type:str]
    password: ENC[AES256_GCM,data:84VLH/83R3dIEseEu3USygXx7Kqs8kx6nfuZC33l2DYV/OEKygksQZ9uI5w=,iv:7diIN85FtcTpleNeaB7uxJD7mpcc/OB4nUHWVZuKdqY=,tag:6+lpzN06HJgIB7pJllNQeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaVkzMGNQc01hdXVNbDBV
            SGhoOFBBRlArRUpwd1l2Mi95Ym9lOHhrT3p3Ci9HcDZjMUtGUWw1NWIyYXl5dHdF
            VWlWV1k1UndzQmRya2gyYXYyWmZRZkkKLS0tIDBnTXJnekh5Z2FwVjhNbWlyanlT
            THhjeENKTkdLcjRsSk0wbUNNbFIzWmMK/rHn6sXnMG3KsY5k7/K+KMpyo1sAoOuB
            p0cVy5IF/ghny43edNgqSh4AV3dyKAcAyn03VJfsq6AVVVZKdIv5+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T13:31:15Z"
    mac: ENC[AES256_GCM,data:LAU9Qd+XzWQuTr2rIBOfHPjT0YHOn3mD790RHGGburB8932i0j52ayXP1CNryWSlOBqtFjd7aBmKd9A2D7m661Q06xhdI1xEWJG2OkaxcZguR9rC88M0zMRmK+JKvrdu4gkylWjieEcGEixGgwluCfd7G/TJJngN3sDFhn4tGLE=,iv:TRUJxn+EiBma2hPq7WPLhxYP+qCfWtiDFM82k3M9tdE=,tag:4P7mwmXb8gaocWwX1+LnBw==,type:str]
    version: 3.13.1
