apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
  namespace: k8up
type: Opaque
stringData:
  access-key: ENC[AES256_GCM,data:GECcgDP/17JWHI8GFFFCJOyliV8=,iv:pg9th2rx6ybtK1+ortdnl7L2C3mFwfnlEfFjehpJq00=,tag:qV4GISYNKLATBsAes+uoQA==,type:str]
  secret-key: ENC[AES256_GCM,data:L7/lClhKdJ1uQoyvdTFBZtIYWpM=,iv:tDHgElOU0AwAjOpaOa6SsfycNV6TMJdzzcd70P8W6lA=,tag:irpMQ0HtMGLPorgNk11y0Q==,type:str]
  repo-ref: ENC[AES256_GCM,data:P7/G3k/Ame3oJlUVj9yBZ8hWivf0S6n45Ac5w/4mcQdnfky5XeJU8jD3h3Y=,iv:Q03NQJoLosZuVxzIkMsgMMf+Fb7SjRlqRQd3MX35VJM=,tag:Hqu2gxAzeOsLUPzpnZpkFw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtelIwUHhpalFiem1POXBk
        cUVJQ1g1TWJLVWhPM3lVRzR1QjRBMFN0cVhrCm5qYldwTllJZkVrVW9FbTRoK1B0
        cmorekI1VGxBQlZpVFVnTmR0MVFyaGsKLS0tIDY3MFdzSy9ZalJsVzdGTzZlVHla
        aXUrSk9QYkoxRElMWStROGVXVjZCc1EKl7JAKG4WWcA6NHHgv+w2ZL5H5foDkHx0
        Pg8kBW6gg9xvDIo2lt+Cp3xjSxSgd5gs/TuLTK54dgPNwZTYVfqoqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T13:01:58Z"
  mac: ENC[AES256_GCM,data:khCxVopP0oCDnVpfLhv5UrohEGdZx0paeCPphS/m639SQoXwko7go9NoxYWx64TPB102e9TCVEbfOajdFYKr23oVbXCZRug+nlrC2TcyBGOpI3jBwUYty7GtmqtPv4tHXFhQB9naSdns6/ETQGbswhqGDfUdD7fekmuNIdibQ+k=,iv:Wlv/chVDqleuO+QSgHPg5HFXfr+cpNRuv4onSHWtu4A=,tag:2MWX5bkL224BfXftKM0b6w==,type:str]
  version: 3.13.1
