apiVersion: apps/v1
kind: Deployment
metadata:
  name: databasus-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: databasus-agent
  template:
    metadata:
      labels:
        app: databasus-agent
    spec:
      containers:
        - name: agent-container
          image: databasus/databasus-agent:latest
          env:
            - name: AGENT_TOKEN
              value: 47d3b53fcfd64f998eb4d3a3eea74994
            - name: AGENT_ID
              value: 257d9212-03d7-4cda-8535-5a3bdf7aa328
