apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr-helm
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`seerr-helm.doink.co.za`)
      services:
        - name: seerr-seerr-chart
          port: 80
  tls:
    secretName: seerr-helm-tls
