---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.12.0
  values:
    longhornUI:
      replicas: 1
    defaultSettings:
      defaultReplicaCount: "1"
      dataLocality: "best-effort"
      replicaAutoBalance: "best-effort"
      storageOverProvisioningPercentage: "500"
      storageReservedPercentage: "10"
      storageMinAvailableCount: "1"
      replicaSoftAntiAffinity: "true"
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
    force: true
  interval: 1h0m0s
  timeout: 30m
