apiVersion: v1
kind: Secret
metadata:
  name: homelab
  namespace: default
type: Opaque
data:
  db1-password: ENC[AES256_GCM,data:jrQF6evb14gj5p03wRAfyw==,iv:MZrF+SWZugTLRbiuhbyJo02jxqM6TfG3Vn02TXtlWOY=,tag:nOSKmIKfuIDcHRJpzmNOsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNEtQRXBlMEE1dlpRRE01
        c2tVOUphTVp6em9Mb3ZCeUN3SXIweEF6WVZNCm5KTFZHSFZuN2RVUFlCb20wbXMz
        QTVTN0hTUjl3RGlMMkF4allEdDRDeE0KLS0tIEozOEduNDZLRExEK0MwZWw0eWhE
        TGV2SEJaV3R2eGlBbm0waTFaN2hUdFEK50ZQxU55wQ3jbfZw8/vqcczzEPkXnMBr
        /t7HSQ8cYdTWjZXe3P3Pz8Bopqb1kuOmQqhb54rPhDsrRuQMPNhQMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-16T17:09:24Z"
  mac: ENC[AES256_GCM,data:qYzNzlxsTwJvQLkXznW6PnLgPKRiWvidwK7Thbx/Ks8ioGPgBjyZfBdzXzTYQXmsa8FZczQ216XavbbDcFNYw7VzR14NmIhI2TvmKYEQUW+YTq0IHUoTGdpLZRyKuDVNMz+y2ffzP9Lzc/JxnvKD+AtxwGMRPubMmeHW5wTmBn0=,iv:cncDw0WU/zCIZ+QnR5hiONNn/ShJYQSNDHXDT+9O8Yk=,tag:HQWnCgIMv6OgftyZKpu6Kw==,type:str]
  version: 3.13.1
