apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: external-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: external-secrets
    kind: SecretStore
  target:
    name: my-app-k8s-secret
  data:
    - secretKey: db-password
      remoteRef:
        key: homelab/db1
        property: password
