apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: external-secrets
spec:
  provider:
    vault:
      server: "http://openbao-openbao:8200"
      path: "secret"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: cy5pN2p6WVp2dTVVc213cmJQd21nM3lrd1gK
