apiVersion: v1
kind: Secret
metadata:
    name: searxng-auth-secret
    namespace: searxng
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:hmfwLjgPvXyNbiBC5uoMVxIPGuvMI6in/MUqvz9nJtnWulQ7X/pJWCRnUw==,iv:M56xEEKekrECJOy6xbvo/5orlzoJX0nnAfl6S2eY2kU=,tag:qafy6r4g17beT2tc7J+P/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NXNxMUdROFJiMnBJWXJ5
            RnE2ZnI4Y2VkUm9XeXpHSlNXT3BkWXRQUUF3CmRTeUQ1VVVXbEFaM0tQcmsvZU4x
            djkrRDdvZ3JZSy9UdElLSGd5a2lJemcKLS0tIDlMZGFDUzN5eGRZTmt0TEt1bXZt
            VW10SkdNZXFSZ3ltamx6ZEdtamxhRHMKKy7XvQ42zLT9mLVUx48ZPp5cMeroF1vU
            PvfmhM2de5b6XDDBhXBwergvzr+muGWFKWPBggxMY3tY7RBeEphclw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T20:15:04Z"
    mac: ENC[AES256_GCM,data:4Shkw6kzSTGiPZ1MnhqpzfOl+MfeF4NRQWlyRRPngb/OtuyQK2c8ZNiYSmOmU7EK1jJGZAfb9L2KM1l4OAsQf87goidgbZf6yCUe8arwUOuOI40Qu20bt2jg7j50x259/Lj1nMly1WF5yAOwkRvXSKsB5rqboaAnrH4gJvmVnYI=,iv:uF9bApLwns9YH3RZTNaH7R1icWi02yAL8tQL0r5VWwE=,tag:fDQ0nWKmDFMo8MaS61vS0Q==,type:str]
    version: 3.13.1
