apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |
    search:
      formats:
        - html
        - json
    engines:
      - name: google
        disabled: false
      - name: bing
        disabled: false
      - name: duckduckgo
        disabled: false
