apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:e2EF5ZbPvG0cJkkqgm9tqT/NjzRK6A==,iv:j+XhY9UVwJhv2Hez+Trhr3IFQBNPIwMYtjGLBfigmzg=,tag:FUmcVm0CoKW2a68+Ny7fdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N00rMGtlN29uNXNFUitX
            L0ZsS2ZSOFdBcWVpQXBKZkIwanlKcEF6T21nCmYvZklqYkVZY254bTJwcDBVeTBs
            WklMcHpMQkJHWmpGYkpRM3hOSzNEc0UKLS0tIGhhK2NXVFRnM3RCZS9QUkNRZlRl
            ZnU2STdCV25YU3h5ZEQycnhlYy9TZDQKaiss868hde2ruVl+CQ49GvmLLq2PztU+
            BGgX5vl6772I7BJvPrCnhzVnPAUIE0B8UjRl7Kfs1BFK7VYc/hBHxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T12:59:35Z"
    mac: ENC[AES256_GCM,data:hPkG9wBkcXD/9iqxwvjR+wnFEIMg/W1gMFES3NRVPrBI1+mZL8EEHOdNnOCzje/0lAX30XTeCoc6mNvFbXAJYWxAvOqRJPqVVmrfWG/TdvDjjC9ZX+rtMfQOnQDn5kGlBVHTkTGgXP0JIWxJeqJchI/hhXZqsfN0OAj8pu3Rr8g=,iv:7XIg4Dxbd7ZWI8R+d2BghoHt4D+BsaCaBTx+Gehf/+g=,tag:tj4tMkhQDOWPFhYjf3jJcA==,type:str]
    version: 3.13.1
