apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-world-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  hostPath:
    path: /tmp/hello-world-pv
    type: DirectoryOrCreate
