apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-data
  namespace: hello-world
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
