apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart:
    spec:
      chart: traefik-crds
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: kube-system
      reconcileStrategy: ChartVersion
      version: "^1.0.0"
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  interval: 1h
  timeout: 10m
