apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: traefik
      reconcileStrategy: ChartVersion
      version: "^39.0.0"
  values:
    image:
      repository: traefik
    deployment:
      podAnnotations:
        prometheus.io/port: "8082"
        prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    service:
      type: LoadBalancer
      ipFamilyPolicy: "PreferDualStack"
    ports:
      web:
        port: 8000
        containerPort: 8000
        exposedPort: 80
        nodePort: 31127
      websecure:
        port: 8443
        containerPort: 8443
        exposedPort: 443
        nodePort: 30755
        proxyProtocol:
          trustedIPs:
            - "192.168.1.0/24"
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
    force: true
  interval: 1h
  timeout: 15m
