apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-passwd
type: Opaque
stringData:
    mqtt_passwd: ENC[AES256_GCM,data:LF24/IREAj0P2TBkuljk5QK/EjwHnmXv6JWqxkiW44ee4ExwKrz9bRqSsFGZ0tBNV2FUIgpzsRyo3vTh0N9DnWPrfXMWcboKAVZs3knCp3L/wTTf9RgBy0j7kY6BWd6aC7hnGvsXrjFArddXdeLW/qV+AQ6HFw==,iv:r9yZOXBIKL4j/ZGzW2oQuBWHZ9H/CtWPhJkQ0tlxhK8=,tag:J9rJ6f4XDp7I8kcxfS9k/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNGhrTUxLRzlsQmVROE1U
            WlpONFBXazJ3OGFSYXR4OVJna0V1QjhkOVJrCjBjSFFiMXE4eURlVFdXNzUycDdH
            K3ZQcC84UlpSKzBwUVZkRnBXOUVzREUKLS0tIHh0TzVPbEVhaEwwUWRpRDJPN0NH
            UG5QTk53a2VyVzBiZ3pyY3JBdVVYSEkKDFI4On/4VAcJhwEw46wx82aazpcBKzmc
            g+khJfLY/EAVDUo9Fa7tWs8wdwHkfHW6XijlueDoLonbIHR5rEaZPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T09:13:01Z"
    mac: ENC[AES256_GCM,data:qQ1k6uE9lLr57sCbbrHCqWP2X5fLsh1xnX56u/J6iLRfr6zM6apYMiOApA4VRqpShOQI07geGbaBXtv/q0igWedHquVHhXHSGoTU21cNRpQd+Pvim9ybeCn8Bu9nJmiwhQzrns4EjnoPk0DX5upG5F5H60j9BBv4E1vLdiG1Zjg=,iv:ErgCVq3JbdEXJlDc7LjVkQa9B0eIw84Yt+U9YLiK9C0=,tag:CtOaAEeOuvwLQy7YUMkslg==,type:str]
    version: 3.13.3
