---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: papra
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: papra
  template:
    metadata:
      labels:
        app: papra
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-data
          image: ghcr.io/papra-hq/papra:26.6.2-rootless
          command:
            - sh
            - -c
            - mkdir -p /app/app-data/db
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              memory: 128Mi
          volumeMounts:
            - mountPath: /app/app-data
              name: papra-app-data
      containers:
        - name: papra
          image: ghcr.io/papra-hq/papra:26.6.2-rootless
          ports:
            - containerPort: 1221
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 768Mi
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: papra-secret
                  key: AUTH_SECRET
            - name: APP_BASE_URL
              value: http://192.168.1.36:31221
            - name: INGESTION_FOLDER_IS_ENABLED
              value: "false"
            - name: DOCUMENT_STORAGE_FILESYSTEM_ROOT
              value: /app/documents
            - name: PGUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - mountPath: /app/app-data
              name: papra-app-data
            - mountPath: /app/documents
              name: papra-documents
      restartPolicy: Always
      volumes:
        - name: papra-app-data
          persistentVolumeClaim:
            claimName: papra-app-data
        - name: papra-documents
          persistentVolumeClaim:
            claimName: papra-documents
---
apiVersion: v1
kind: Service
metadata:
  name: papra
spec:
  type: NodePort
  selector:
    app: papra
  ports:
    - port: 1221
      targetPort: 1221
      nodePort: 31221
      protocol: TCP
