---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papra-app-data
  labels:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papra-documents
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-documents
  resources:
    requests:
      storage: 10Ti
