apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:p+VHVz8xFKYKfFbwHO8/ZJd8lkvMcrzRbBbFH8Eo2EOvfXkmX7Q9Lh9jXKKF9vVlKzC2cIY=,iv:OgN9OzvVHiFpA7l7eIb0iGbi/8TZzG3xCt0SsSm+eyQ=,tag:hYLfpY9NY1vTel3BcmTtfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWXFYSGMvOE0xTmJSTEp0
            S1k4MnlHdjdGenVmMndtZTdXYmx6TzBjN1ZNClhPcjc5T2FQa2tiYkRGSTk0S2tq
            amJUNVpKNFdPVnNxSGFhMmIxTHdpblEKLS0tIGhyWE1MeWhIU1BQOUQ1VVBhL21P
            aFRCellIa1E3YnBISFk2RjZ6aGNLL2sKQp1jeYS8dEEfYW3htdtL/lY5DvtMbmWY
            1adz3ECjkVzCE1OdUVrFp1inbq/1vaF23rlb9eICJGmkFS+0fX9iDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T19:44:58Z"
    mac: ENC[AES256_GCM,data:kKqk78bbUUpwLTZAyifxTQQjpad4/CNqLKlxThQ6VR16cSuH3dQMFCcA4JVjW5RKnUkPbeYv+S6FVMmdlpPeKWo2FrjqmSKMWYqmceQBHalP0CcK8sitEGbQqgRglb8YvEsEuFkZTY/NmL13VEqXz85lQML01PqXzKinQPZIECY=,iv:hCJ0HLz1YXBNtsupBvQhGDhILYq9rXKkHSElOCt5/cM=,tag:s0dm2u4rhyK7QMxhI/weXQ==,type:str]
    version: 3.13.1
