apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:60p+I8io06m9S8g2n9XgCMqGUDNX/MkXOWCTvzHCoYY6BWg5iQ==,iv:nhsLJpMfKREGlP2dm1sMZNEZTzQqb6Nlg42L7IbgezQ=,tag:h7c8eDioDWrJgPMwEbk7lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWXFYSGMvOE0xTmJSTEp0
            S1k4MnlHdjdGenVmMndtZTdXYmx6TzBjN1ZNClhPcjc5T2FQa2tiYkRGSTk0S2tq
            amJUNVpKNFdPVnNxSGFhMmIxTHdpblEKLS0tIGhyWE1MeWhIU1BQOUQ1VVBhL21P
            aFRCellIa1E3YnBISFk2RjZ6aGNLL2sKQp1jeYS8dEEfYW3htdtL/lY5DvtMbmWY
            1adz3ECjkVzCE1OdUVrFp1inbq/1vaF23rlb9eICJGmkFS+0fX9iDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T18:57:04Z"
    mac: ENC[AES256_GCM,data:BrBK8EoNPWSP/sS+rBlJGOjBH/xmB3PDsPDAvih4oUH+cvHR2TaqFrMrnu18GiCaPq/fQI25XtG0Uk5ls8ki7q/vpoKx0davBVdWo0gEGRqWkvXoJUWkeQj2UWo0Zuxff9UGEPfsElwxG7Uplup4HeuRQ72EG9jmYY/4/uhiNNs=,iv:UC5Bsvo6HxrRVYvLmb3rBxBbhxlCaSzIIxGoCbrohNU=,tag:8sg0sDcbJj7yaulhWH5R6g==,type:str]
    version: 3.13.1
