registry_username: ENC[AES256_GCM,data:JeqUo0E=,iv:YhjNr+aJZKHUhDW/zyP4h2lxR+olLF89oCjp3VzXgIU=,tag:24IZXy+/mleSaIgeVguQVQ==,type:str]
registry_password: ENC[AES256_GCM,data:eDZRGnJsqS1c7OcIsI6tRiixnzLzWHs5SIvWXhn7kTNOp2vE,iv:4tOjdkgAuCryVzwqFXje6uRHk52wWqdX4OxQPWqOrpo=,tag:UhuQNEDMcVUMxzp4A9Zz9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VWhWdEVSd0xPZnhWSENO
            OGlDeHVpcDRTZ1BObTI3NnFJN1RkbEpYQ21BCkV0dFFYU0lQQk9ndEdoRVNwKzVy
            VDlUY1hjelBPVTVXOEpxQ3BUaHRMVjQKLS0tIGh3MWNUYmM3VDdEbVE4UGhhd1Vr
            Nm5tNVAvZGdZcndtay85SHVCVGUwNVUK+Ga2itC2T3Ns4fwPue6eTEHPhyami5n+
            r78mgsH1ea0hgOm2Dk6cAWQULtVzMFxWnrwB5ZoFaiHHYVJROp2LBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: .*
    lastmodified: "2026-07-07T11:49:17Z"
    mac: ENC[AES256_GCM,data:AeBpvCdK3xVgEEcqnug7Dtc96+AXK8qoIBta6ukToLQFUa7essoAqK+jUUpIio27CkzGoJsiOSXpnXyhaWxmEYvuy1GiaBZNwmM5llkf3viQ//3ZDjEZQ/P47EafQkD9V71NwfR76hyjO25m1M4cbE99jWZ7CHiUChtpTvcz+EE=,iv:A/ceAje2oJHEmOLl77lV4OEnK+o0X+1ML1Cq8lI3cHk=,tag:X9BMsWO4X4mEPZ1hJLzn1w==,type:str]
    version: 3.13.2
