---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
  labels:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
