---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go2rtc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: go2rtc
  template:
    metadata:
      labels:
        app: go2rtc
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: go2rtc
          image: docker.io/alexxit/go2rtc:1.9.14
          env:
            - name: TZ
              value: Africa/Johannesburg
          ports:
            - containerPort: 1984
              protocol: TCP
            - containerPort: 8554
              protocol: TCP
            - containerPort: 8555
              protocol: TCP
            - containerPort: 8555
              protocol: UDP
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: go2rtc-config
            items:
              - key: go2rtc.yaml
                path: go2rtc.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: go2rtc
spec:
  type: NodePort
  selector:
    app: go2rtc
  ports:
    - name: api
      port: 1984
      targetPort: 1984
      nodePort: 31984
      protocol: TCP
    - name: rtsp
      port: 8554
      targetPort: 8554
      nodePort: 31854
      protocol: TCP
    - name: webrtc
      port: 8555
      targetPort: 8555
      nodePort: 31855
      protocol: TCP
    - name: webrtc-udp
      port: 8555
      targetPort: 8555
      nodePort: 31856
      protocol: UDP
