apiVersion: v1
kind: Secret
metadata:
    name: go2rtc-config
type: Opaque
stringData:
    go2rtc.yaml: ENC[AES256_GCM,data:hKcQtQK9PF3P1kztOW7xY2OEdQ2w/ib9xXj7t7TZ34lVfncuQxUFnZ2jPG92JR1BM1aIJKYiZan3SckLLAVFnXvDjaVdPtGFXEPLrq27d/d6Zhs3qG1tM1q9HmfnGKF1xZVGCsu3hxq2H7FV8I79CKBH83OsDiCbDFYceojFKtYkX8YxQ6rLuo4CZ6ewZGxkiNEGQr8MduupSOtGW6Mhs2soUEkH18f8AjPEyvyhorkpnJqyz2fmrSLHGYXfSjYHBykN3melZw==,iv:T1S+BaJfx3+HqVrUM/aGmmZsqzDtsL0OKZOm+paLrSM=,tag:06aYG0amqXYzlmBRxpLHtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEelBWZ0JmNEFCNG9CM0hJ
            TTBOUTl6ZjAxN0VrYjdnMUpOQ2QyYUtOUm1vCitPU0xOREhBTnIvZU05U0VaWWkv
            anpLa0IxS0tsaEFuMXFuUG9ObGJzVzgKLS0tIGdGM0hla0d0M1dBUFJvc3pKaG9r
            U200YWJlVTBybnl4T3VKMUE3QXRBSG8KzaVN7ifu+A8yq0ye7Kw8vLxVSwxqqKCW
            q7KXOsrg0IwAiFmEaTIKsMDF3BPjXXXsr0Oj8kfdRUynFM+tCyzMdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T12:51:17Z"
    mac: ENC[AES256_GCM,data:dYTSuMatC/GCGcZEOVs7DvrOWs4hYbHfheEZ+Nn3jE3W3WkOcsfbmggcn5CxV1tsI5sWFozHLawiXX9Q2ryO73OklCKdKSyeGT4n5mqTTgiJdg++3XprhUeLsXPBRLYCwc9qaXwSJwgTksqAK7MjO2rAnpXR1cotA2kQhyzjBmE=,iv:wnEIuipl8JUNBQmoZ5u3h2oyn8iS4NSvUWvHtZEtzfw=,tag:XgvQ2CB+swBMy+K5gbxF2g==,type:str]
    version: 3.13.3
