apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-secret
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:68SvAiLxdHJ4o16R8VArIh/mqlsNdVyrnj+JCKSdolfYF38cfzgfAvmaP77vvxflzyn0KrSxyEamRdFKdnqq7oqMj63kj1UJMcBFrcm3k37Yj4+CBXyzxk7/+ZM+VcLQA1b/X0Z1wK7YdohOxbOJXw==,iv:A0vFrhW6jm6ImzCNA8So8OsTXKXK2Rh3NiZP4Bns8ts=,tag:L/6T+ZC33NdiN5nwCKf7gg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb3pUekRkcTU0RnNmYXM4
            UHN2Q2IvdjBxVkZNdHQ0TDIzRUZydStLRmxrCm1BQkZiWmJqUHI3MU1hOTZNbjZx
            Q0crc0xkVVp0aE9PWldkNFd1QTU0M2sKLS0tIHFicXBVc3dYUE50WWYzWHlTdWZN
            cGpFVk5IbWMrNURydE0vWGQyaTJSM1UKySfUGD5E5JOmqVdfQ5ojgARRa4BrwpxO
            hCepiZ76JliDu8GzrYtkGADuGMOFPOGbpi2YUP9Cn+mSaMZq8bW5hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T21:10:55Z"
    mac: ENC[AES256_GCM,data:v8g260vDgTjkrDqvdgnLqCb1+rS3QRMVkKZX8ztbWeDVf5csZyZNX3EEvMtE3xzvg0jjDaX8tu1KOfRduOgK6j6QKr0NirslS+SOXl1FiBLpnfvGTWHk5O998wKcJUAKyBP3j3hEkL4AlnM4eHW6eJ5oD9CoIzBnD6O02DUsg1Q=,iv:23RRd3Iu9HAevqT6xhWLodDox09bhu1sSINr5z6E0sA=,tag:G+a16zgFryaN9AtHbbqmKw==,type:str]
    version: 3.13.1
