apiVersion: v1
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:qAGA0V12XpQj2TirFqFNvhUl1k19GgPOopewnsQyDkc6Rac6mIMTaizUPdPiOdcA3xQKPyNSsOEjxd7bCsGYsDrMZvsle2M4KhIPQAp8AGb2tcrJepZPJyyrxJyJxnwzGDaS5WOMRpxOg1+VqT75IQ==,iv:dtpFyKgLAqI50C5Zb9WTPUnuM/zlR6jAgDxzjTnLxb0=,tag:VrCE/KTEyKxJlxEvWc0y2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUnJTeFIwKzFZd25GL2Vs
            Tzd2VGNwSHV1enZTM1Z6ZEQyWVEzUGlPVVFFCm9WV2oxVFVNUEl0VHNnOGVuZ3Rm
            RG1oWnFxM1hOZWRSd0pWVnJJSFhYNncKLS0tIEhmOTc3bzAxWUw0MEk4a01DTHli
            WkF2dUdobVpGNGwrV0ZxZ2k5eDB5Z1kK5REjk9xusk7LADdUH4MBumroSMfMLdd1
            IfD+bg2bsJUgjVkPqW1Jt/Z9VAQEc8P91q2dlQDyXR3aGArFgewu2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1palh43zgjqhkankzl4gltrhvruyucfefph4tlzlp00t8kvp3xqaqkvxjul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T21:16:28Z"
    mac: ENC[AES256_GCM,data:gNCZpqKU4aoDBHjvZLIxjULmFhVUytcdJzfjt3JUSIjqfAus+NgCZzEzB+D6Xpe/NVLfiFe2gQt8NSSyHgP7l0P+HlCLairU3B3ubCsseXkqevSborMwzeRArjzXu4ES+xIlehcPRkds+3+xX0nCiwyuWvba1yALeEaJ9A/V+OQ=,iv:+exCtU+HejgvlW9D8kPhtXchhsHLwo3LCeSy2PskT18=,tag:KQ7rs7j4hD1VUs7ppD2xQQ==,type:str]
    version: 3.13.1
